# Generated by Django 2.0 on 2018-11-23 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operator', '0002_auto_20181121_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': '用户地址', 'verbose_name_plural': '用户地址'},
        ),
    ]
