# Generated by Django 2.0 on 2018-11-21 14:03

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsname', models.CharField(max_length=64)),
                ('goodsprice', models.FloatField(default=0)),
                ('goodsnum', models.IntegerField(default=1)),
                ('goodsdesc', DjangoUeditor.models.UEditorField(default='商品描述')),
                ('add_time', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=62)),
                ('goodscategory_type', models.CharField(choices=[('1', '一级目录'), ('2', '二级目录'), ('3', '三级目录')], max_length=32)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '商品类别',
                'verbose_name_plural': '商品类别',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='goodstype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory'),
        ),
    ]
