# Generated by Django 2.0 on 2018-11-21 14:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordersn', models.CharField(max_length=32)),
                ('ordernum', models.IntegerField(default=1)),
                ('orderstatus', models.CharField(choices=[('1', '完成'), ('2', '待支付'), ('3', '取消'), ('4', '其他')], default='', max_length=32)),
                ('addtime', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsnum', models.IntegerField(default=1)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('goodsname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
    ]
