# Generated by Django 2.0 on 2018-11-21 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0001_initial'),
        ('trade', '0001_initial'),
        ('user_operator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='goodsinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='useradd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_operator.UserAddress'),
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcard',
            unique_together={('user', 'goodsname')},
        ),
    ]
