# Generated by Django 2.0 on 2018-11-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20181121_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='useradd',
        ),
    ]
